version: '3'

services:
  db:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
      MYSQL_USER: userdb
      MYSQL_PASSWORD: passstrong
      MYSQL_AUTHENTICATION_PLUGIN: caching_sha2_password
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - nodeapp


  nodejs:
    build: .
    container_name: nodejs
    entrypoint: dockerize -wait tcp://db:3306  docker-entrypoint.sh sh -c "npm install && node server.js"
    volumes:
      - ./app:/usr/src/app
    ports:
      - "3000:3000"
    command: npm start
    networks:
      - nodeapp
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - nodeapp
    depends_on:
      - nodejs

networks:
  nodeapp:
    driver: bridge
